server:
  port: 8999
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/merry_christmas?serverTimezone=UTC
    username: root
    password: root12345
logging:
  file:
    path: "log"
  level:
    root: info