server:
  port: 8899
spring:
  profiles:
    active: localnetwork
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.150:3306/merry_christmas?serverTimezone=UTC
    username: root
    password: root12345
logging:
  file:
    path: "C:/coder/log/log_local"
  level:
    root: info